#!/usr/bin/with-contenv bash

# make our folders
mkdir -p /config/.spacemacs.d

# initilzie Signal so it will start in fullscreen
if [ ! -e /config/.config/Signal ]; then
    echo '## [ 1 ] #############################################################'
    ln -s /config/data /config/.config/Signal
fi
if [ ! -e /config/.config/Signal/ephemeral.json ]; then
    echo '## [ 2 ] #############################################################'
    cp /opt/Signal/ephemeral.json /config/.config/Signal/ephemeral.json
fi
echo '----------------------------------------------------------------------'

# Setup credentials based on container's environment
sed -i 's|"password":"abc",|"password":"kjhbouygiuvhgvghv",|' /gclient/app.js
sed -i "s#process.env.PASSWORD || 'abc';#process.env.PASSWORD || 'kjhbouygiuvhgvghv';#" /gclient/maketoken.js
if ([ -n "$GUAC_USER" ] || [ -n "$GUAC_PASS" ]) && [ -z "$PASSWORD" ]; then
    echo '
********************************************************
********************************************************
****                                                ****
****  GUAC_USER and GUAC_PASS vars are deprecated   ****
****                                                ****
****  Temporary credentials are being set:          ****
****                                                ****
****  User: abc                                     ****
****  Pass: abc                                     ****
****                                                ****
****                                                ****
****  See the readme for new credential info        ****
****                                                ****
****                                                ****
********************************************************
********************************************************'
elif [ -n "$PASSWORD" ]; then
    echo "abc:${PASSWORD}" | chpasswd
    echo "Setting password from environment variable."
else 
    echo "abc:kjhbouygiuvhgvghv" | chpasswd
    echo "No password is set for the interface."
fi

# permissions
chown -R abc:abc \
    /config
